API for ocm ranking (still alpha), FIX ghost play count ocm, unlimited ghost stamp bug, give meter reward bug, etc
ProjectAsakura/Bayshore pull request #42
Opened 2022-09-08 15:20 UTC by ghkkk090

current PR log :
-Fix ghost play count when retiring ocm
-API for ocm ranking (not sure if this already correct)
-Fix unlimited ghost stamp return (hopefully no more of this)
-Fix give meter reward bug if playCount still 0
-Hopefully fix ocm HoF bug 
-Fix duplicate id in carOrder
-Fix OCM HoF wrong shopName

2022-09-09 11:47 UTC, ry00001 requested changes

2022-09-09 11:47 UTC, ry00001 commented on src/index.ts
> +http.createServer(apiApp).listen(PORT_API, '0.0.0.0', 511, () => {
Port 511 is too low.

2022-09-10 04:01 UTC, ghkkk090 commented on src/index.ts
> +http.createServer(apiApp).listen(PORT_API, '0.0.0.0', 511, () => {
sry.. i have no idea about this

2022-09-14 11:58 UTC, ry00001 approved these changes
looks good

2022-09-14 11:58 UTC, ry00001 commented on src/index.ts
> +const PORT_API = 9003;
poggers

2022-09-14 11:58 UTC, ry00001 commented on src/modules/ghost.ts
> +			let checkBeatedCar = await prisma.carStampTarget.findMany({
whats this formatting about?

2022-09-14 11:58 UTC, merged