Fixed issue with not working with newer node.js versions
ProjectAsakura/Bayshore pull request #79
Opened 2024-04-20 14:43 UTC by leezhiwei

Hi, I managed to fix the issues with node.js by removing `extends Module` in the various modules, and updated the dependencies. #78

2024-04-22 11:57 UTC, lostkagamine commented
Thank you!

2024-04-22 12:11 UTC, leezhiwei commented
I hope my work helps out the community ofc.

2024-04-22 12:29 UTC, leezhiwei commented
Need some help testing significant node versions. I know 20+ works, 16 also works too, according to my screenshot below. ![Screenshot_20240422-202246.png](https://github.com/ProjectAsakura/Bayshore/assets/13075070/6edb227c-b33c-4a0e-bedb-60f0e54ec37c)

2024-04-22 12:32 UTC, lostkagamine requested changes
Some changes in this pull request are completely unnecessary.

2024-04-22 12:32 UTC, lostkagamine commented on updatecar.pgsql
> +UPDATE "Car" SET
What is this file even doing?

2024-04-22 12:32 UTC, lostkagamine commented on package.json
> +    "typescript": "^4.0"
Why downgrade TypeScript???

2024-04-22 12:32 UTC, lostkagamine commented on package.json
> +    "long": "4.0.0",
Don't downgrade packages if you don't know what you're doing.

2024-04-22 12:32 UTC, lostkagamine commented on src/modules/cars.ts
> -export default class CarModule extends Module {
Why?

2024-04-22 12:32 UTC, lostkagamine commented on src/modules/util/common.ts
> +        var resp = Buffer.from(end);
This intermediate variable isn't needed. This change is unnecessary.

2024-04-22 12:36 UTC, leezhiwei commented on updatecar.pgsql
> +UPDATE "Car" SET
Sorry. Was testing and removed it? Why is it still in the repo.

2024-04-22 12:37 UTC, leezhiwei commented on src/modules/cars.ts
> -export default class CarModule extends Module {
This one was the change that made it work, this line of code resolved it.

2024-04-22 12:38 UTC, leezhiwei commented on src/modules/util/common.ts
> +        var resp = Buffer.from(end);
I agree it is. Sorry was debugging and accidentally left it in.

2024-04-22 12:39 UTC, lostkagamine commented on src/modules/cars.ts
> -export default class CarModule extends Module {
That's odd. Why wasn't it booting with the `extends` in place?

2024-04-22 12:40 UTC, lostkagamine commented on updatecar.pgsql
> +UPDATE "Car" SET
You can `git rm` it.

2024-04-22 12:41 UTC, leezhiwei commented
Honestly speaking. I have no idea why the TS downgraded. All I did was a `npm i`

2024-04-22 13:19 UTC, leezhiwei commented
Honestly speaking. I have no idea why the TS downgraded. All I did was a `npm i`

2024-04-22 13:19 UTC, leezhiwei commented
@lostkagamine currently build (on this repo) of this results in this Long type error. ![Screenshot_20240422-211853.png](https://github.com/ProjectAsakura/Bayshore/assets/13075070/f8796653-4bc1-41b0-8b8f-20ebd969c765)

2024-04-22 13:24 UTC, leezhiwei commented
Why my long was downgraded was due to this stackoverflow. https://stackoverflow.com/questions/58159115/error-ts2304-cannot-find-name-long-when-compiling-typescript-with-google-ap

2024-04-22 13:49 UTC, leezhiwei commented
> For the future, please post text logs instead of screenshots, it makes it really hard to read.

Sorry. Used to screenshots as logs here in Asia... I'll do codeblock quotes.... Sorry.

2024-04-22 13:56 UTC, leezhiwei commented
Next this error appears
```
lee@mainservlee8219 ~/Bayshore (master)> yarn dev
yarn run v1.22.19
$ tsc && node dist
Loading config file...
/home/lee/Bayshore/dist/modules/cars.js:13
        function __() { this.constructor = d; }
                                         ^

TypeError: Cannot set property constructor of [object Ob
ject] which has only a getter
    at new __ (/home/lee/Bayshore/dist/modules/cars.js:1
3:42)
    at __extends (/home/lee/Bayshore/dist/modules/cars.j
s:14:84)
    at /home/lee/Bayshore/dist/modules/cars.js:98:5
    at Object.<anonymous> (/home/lee/Bayshore/dist/modul
es/cars.js:302:2)
    at Module._compile (node:internal/modules/cjs/loader
:1198:14)
    at Object.Module._extensions..js (node:internal/modu
les/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:107
6:32)
    at Function.Module._load (node:internal/modules/cjs/
loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:
1100:19)
    at require (node:internal/modules/cjs/helpers:119:18
)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for docum
entation about this command.
```

2024-04-22 14:09 UTC, leezhiwei commented
```
Loading config file...
TypeError: Cannot set property constructor of [object Ob
ject] which has only a getter
    at new __ (/home/lee/Bayshore/src/modules/cars.ts:13
:42)use('/', appRouter);
    at __extends (/home/lee/Bayshore/src/modules/cars.ts
:14:84)
    at /home/lee/Bayshore/src/modules/cars.ts:15:40
    at Object.<anonymous> (/home/lee/Bayshore/src/module
s/cars.ts:255:2)
    at Module._compile (node:internal/modules/cjs/loader
:1198:14)
    at Module.m._compile (/usr/lib/node_modules/ts-node/
src/index.ts:1618:23)ET / Mucha Server
    at Module._extensions..js (node:internal/modules/cjs
/loader:1252:10)                      120,25        71%
    at Object.require.extensions.<computed> [as .ts] (/u
sr/lib/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:107
6:32)
    at Function.Module._load (node:internal/modules/cjs/
loader:911:12)
```
This is the error that is fixed by removing `extends Module`

2024-04-22 14:14 UTC, leezhiwei commented
The `updatecar.pgsql` is not included in the latest commit. FYI.

2024-05-11 04:21 UTC, leezhiwei commented
Hi guys?

2024-08-23 12:49 UTC, leezhiwei commented
I'll try and rebase my code, without the sql script being in the history and will request another PR. @lostkagamine please close this PR while I reset my branch. This can be archived for informational sake.

2024-08-23 13:23 UTC, lostkagamine commented
Thank you; closed as requested.

2024-08-23 13:23 UTC, closed without merging